### PR TITLE
ES120MC1_ADAPTER

### PR DESCRIPTION
**Pull request by XueNianOfficial**

### CODE REVIEW

**Comment by vroland** [comment]
Thanks, looks like I missed this, sorry. I assume the pictures mean this is tested and working?

**Comment by 3058132083** [comment]
> 谢谢，看起来我错过了这个，抱歉。我猜图片意味着这已经过测试并且工作正常吗？

Yes,the adapter works well,but I designed it with EasyEDA，so I don't have a KiCAD file.
And I have given up the project as it was too slow，I switched to a project that used FPGAs（Glider）

**Comment by vroland** [comment]
Ok, thanks for contributing in any case. As it's not kicad, it will not show up on the auto-generated hardware page, but it will be in the repo for whoever needs it.

**Review by vroland — APPROVED** [review]

**Comment by Uri-Tauber** [comment]
Hi, @XueNianOfficial, were you able to drive the ES120MC1 with Glider?
Also, can you explain why its necessary to replace the connector which came with the screen?
Thanks.

**Pull request merged**
